/** GPU title simulation과 magnetic-shield render pass가 공유하는 compact interaction ABI입니다. */
export const TITLE_WEBGPU_SHIELD_INTERACTION_MAX_IMPACTS = 12;
export const TITLE_WEBGPU_SHIELD_INTERACTION_MAX_DENTS = 16;

const VEC4_BYTE_SIZE = 16;
const HEADER_VEC4_COUNT = 1;

export const TITLE_WEBGPU_SHIELD_INTERACTION_ABI = Object.freeze({
    HEADER_BYTE_OFFSET: 0,
    HEADER_BYTE_SIZE: HEADER_VEC4_COUNT * VEC4_BYTE_SIZE,
    IMPACT_COUNT_U32_OFFSET: 0,
    DENT_COUNT_U32_OFFSET: 1,
    IMPACT_BYTE_OFFSET: HEADER_VEC4_COUNT * VEC4_BYTE_SIZE,
    IMPACT_BYTE_SIZE: TITLE_WEBGPU_SHIELD_INTERACTION_MAX_IMPACTS * VEC4_BYTE_SIZE,
    DENT_BYTE_OFFSET: (
        HEADER_VEC4_COUNT + TITLE_WEBGPU_SHIELD_INTERACTION_MAX_IMPACTS
    ) * VEC4_BYTE_SIZE,
    DENT_BYTE_SIZE: TITLE_WEBGPU_SHIELD_INTERACTION_MAX_DENTS * VEC4_BYTE_SIZE,
    BYTE_SIZE: (
        HEADER_VEC4_COUNT
        + TITLE_WEBGPU_SHIELD_INTERACTION_MAX_IMPACTS
        + TITLE_WEBGPU_SHIELD_INTERACTION_MAX_DENTS
    ) * VEC4_BYTE_SIZE
});
