export const WAVE_RUN_STATE = Object.freeze({
    INACTIVE: 'INACTIVE',
    WAVE_ACTIVE: 'WAVE_ACTIVE',
    DEADLINE_SPAWN_DRAIN: 'DEADLINE_SPAWN_DRAIN',
    OVERTIME: 'OVERTIME',
    CLEAR_CANDIDATE: 'CLEAR_CANDIDATE',
    SETTLEMENT_PENDING: 'SETTLEMENT_PENDING',
    SHOP_OPENING: 'SHOP_OPENING',
    SHOP: 'SHOP',
    NEXT_WAVE_PREPARE: 'NEXT_WAVE_PREPARE',
    MAP_CLEAR_READY: 'MAP_CLEAR_READY',
    RUN_DEFEATED: 'RUN_DEFEATED',
    DESTROYED: 'DESTROYED'
});

export const WAVE_RUN_FACT_TYPE = Object.freeze({
    WAVE_STARTED: 'WaveStarted',
    WAVE_DEADLINE_REACHED: 'WaveDeadlineReached',
    OVERTIME_STARTED: 'OvertimeStarted',
    OVERTIME_PULSE: 'OvertimePulse',
    WAVE_COMPLETED: 'WaveCompleted',
    WAVE_FAILED: 'WaveFailed',
    NEXT_WAVE_READY: 'NextWaveReady',
    MAP_CLEAR_READY: 'MapClearReady'
});

export const WAVE_RUN_RESULT_CODE = Object.freeze({
    ACCEPTED: 'ACCEPTED',
    DEFERRED: 'DEFERRED',
    SOURCE_CHANGED: 'SOURCE_CHANGED',
    WRONG_PHASE: 'WRONG_PHASE',
    QUIESCENCE_NOT_PROVEN: 'QUIESCENCE_NOT_PROVEN',
    SHOP_NOT_READY: 'SHOP_NOT_READY',
    TRANSACTION_CONFLICT: 'TRANSACTION_CONFLICT',
    RUN_DEFEATED: 'RUN_DEFEATED',
    DESTROYED: 'DESTROYED'
});

export const WAVE_RUN_FINAL_CONTINUE_RESULT = Object.freeze({
    MAP_CLEAR_READY: 'MAP_CLEAR_READY'
});

export const WAVE_RUN_TERMINAL_STATES = Object.freeze([
    WAVE_RUN_STATE.MAP_CLEAR_READY,
    WAVE_RUN_STATE.RUN_DEFEATED,
    WAVE_RUN_STATE.DESTROYED
]);
